train_clusters: 
task_name:
prompt_pool_path: ???
cuda_device: 'cuda:0'
out_file: ???
n_docs: ???
prompt_setup_type: ???
batch_size: 50
model_name: 'sentence-transformers/paraphrase-mpnet-base-v2'
cache_dir: ???
model:
  _target_: src.models.embedder.IndexEmbedder
  model_name: ${model_name}
  cache_dir: ${cache_dir}
